GET http://ec2-3-141-42-234.us-east-2.compute.amazonaws.com:3000/login/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7Im5hbWUiOiJBQkMiLCJlbWFpbCI6IlhZUFoifSwiaWF0IjoxNjIzNzUwOTk3LCJleHAiOjE2MjM3NTE1OTd9.Y5lrZtS20CijD2eg7FwFLj6iHPwpLu4NiDOeV3Qvos4
###
POST http://localhost:3000/createUser
Content-Type: application/json

{
    "name": "Testing",
    "email": "test@gmail.com",
    "password": "123456789"
}
###
POST http://localhost:3000/getAllPosts
Content-Type: application/json

{
    "user_id": "612a3e6af2fb5ae3bc53722f"
}

###
POST http://localhost:3000/getUserById
Content-Type: application/json

{
    "id": "612a3e6af2fb5ae3bc53722f"
}

###
POST http://localhost:3000/updateLikes
Content-Type: application/json

{
    "user_id": "612a3e6af2fb5ae3bc53722f",
    "likes": "1"
}

###
POST http://localhost:3000/createPost
Content-Type: application/json

{
    "user_id": "612b2789f9070757430e6107",
    "likes": "0",
    "comments": "2",
    "value": "djksafjksbdfks"
}